package com.ke.controller;


import com.ke.ClassDetail;
import com.ke.Student;
import com.ke.StudentNotFoundException;
import com.ke.StudentRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


import java.util.Optional;

@Controller
@CrossOrigin
@EnableAutoConfiguration
public class MainController {

    @RequestMapping("/")
    @ResponseBody
    String home() {
        return "Hello Name!";
    }

    @Autowired
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private StudentRepository studentRepository;

    @PostMapping(path="/adds") // Map ONLY POST Requests
    public @ResponseBody
    String addNewStudent (@RequestParam String name, String grade) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Student n = new Student();
        n.setName(name);
        n.setGrade(grade);
        studentRepository.save(n);
        return "Saved";
    }

    @PostMapping(value = "/addJson")
    public @ResponseBody
    String getJsonVal(@RequestBody Student student) {
        studentRepository.save(student);
        return "saved";
    }

    @GetMapping(path="/students")
    public @ResponseBody Iterable<Student> getAllUsers() {
        // This returns a JSON or XML with the users
        return studentRepository.findAll();
    }

    @GetMapping(path="/studentsSelect/{name}")
    public @ResponseBody Iterable<Student> getSearchedStudents(@PathVariable String name) {
        // This returns a JSON or XML with the users
        return studentRepository.findByPrefix(name);
    }

    // can be used in event
    @GetMapping("/students/{id}")
    @ResponseBody
    Student getOne(@PathVariable Integer id) {
        return studentRepository.findById(id)
                .orElseThrow(() -> new StudentNotFoundException(id));
    }

    // can be used in event update
    @PutMapping("/students/{id}")
    @ResponseBody
    Optional<Student> replaceStudent(@RequestBody Student newStudent, @PathVariable Integer id) {
        return studentRepository.findById(id)
                .map(student -> {
                    student.setName(newStudent.getName());
                    student.setGrade(newStudent.getGrade());
                    student.setPayment(newStudent.getPayment()); //TODO self increment by time
                    student.setPaymentPerClass((newStudent.getPaymentPerClass()));
                    student.setDate(newStudent.getDate());
                    if (newStudent.getClassDetail() != null) //FIXME is it necessary
                        student.getClassDetail().addAll(newStudent.getClassDetail());
                    return studentRepository.save(student);
                });
    }

    @DeleteMapping("/employees/{id}")
    @ResponseBody
    void deleteStudent(@PathVariable Integer id) {
        studentRepository.deleteById(id);
    }


    /** Events */
    @GetMapping(path="/students/events")
    public @ResponseBody
    Iterable<ClassDetail> getAllEvent() {
        // This returns a JSON or XML with the users
        return studentRepository.findAllByClassDetails();
    }

    @PutMapping(value = "/event")
    public @ResponseBody
    String addClass(@RequestBody ClassDetail classDetail) {
        studentRepository.addClass(classDetail);

        return "saved";
    }

    @DeleteMapping("/event/{name}/{classId}")
    @ResponseBody
    void deleteEvent(@PathVariable String name, @PathVariable Integer classId) {
        studentRepository.deleteByClassId(name, classId);
    }





}
